[tools]
babashka = "latest"
black = "latest"
fd = "latest"
harper-ls = "latest"
helm = "latest"
lazygit = "0.52.0"
shfmt = "latest"
stylua = "latest"
yamlfmt = "latest"
yq = "latest"
clangd = "21.1.8"

[settings]
idiomatic_version_file_enable_tools = ["python"]
